// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/model/ent/entcomment"
	"backend/internal/model/ent/entpost"
	"backend/internal/model/ent/entuser"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntCommentCreate is the builder for creating a EntComment entity.
type EntCommentCreate struct {
	config
	mutation *EntCommentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "createdAt" field.
func (ecc *EntCommentCreate) SetCreatedAt(t time.Time) *EntCommentCreate {
	ecc.mutation.SetCreatedAt(t)
	return ecc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (ecc *EntCommentCreate) SetNillableCreatedAt(t *time.Time) *EntCommentCreate {
	if t != nil {
		ecc.SetCreatedAt(*t)
	}
	return ecc
}

// SetUpdatedAt sets the "updatedAt" field.
func (ecc *EntCommentCreate) SetUpdatedAt(t time.Time) *EntCommentCreate {
	ecc.mutation.SetUpdatedAt(t)
	return ecc
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (ecc *EntCommentCreate) SetNillableUpdatedAt(t *time.Time) *EntCommentCreate {
	if t != nil {
		ecc.SetUpdatedAt(*t)
	}
	return ecc
}

// SetTimestamp sets the "timestamp" field.
func (ecc *EntCommentCreate) SetTimestamp(t time.Time) *EntCommentCreate {
	ecc.mutation.SetTimestamp(t)
	return ecc
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (ecc *EntCommentCreate) SetNillableTimestamp(t *time.Time) *EntCommentCreate {
	if t != nil {
		ecc.SetTimestamp(*t)
	}
	return ecc
}

// SetContent sets the "content" field.
func (ecc *EntCommentCreate) SetContent(s string) *EntCommentCreate {
	ecc.mutation.SetContent(s)
	return ecc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (ecc *EntCommentCreate) SetNillableContent(s *string) *EntCommentCreate {
	if s != nil {
		ecc.SetContent(*s)
	}
	return ecc
}

// SetShare sets the "share" field.
func (ecc *EntCommentCreate) SetShare(e entcomment.Share) *EntCommentCreate {
	ecc.mutation.SetShare(e)
	return ecc
}

// SetNillableShare sets the "share" field if the given value is not nil.
func (ecc *EntCommentCreate) SetNillableShare(e *entcomment.Share) *EntCommentCreate {
	if e != nil {
		ecc.SetShare(*e)
	}
	return ecc
}

// SetBelongsToID sets the "belongsTo" edge to the EntPost entity by ID.
func (ecc *EntCommentCreate) SetBelongsToID(id int) *EntCommentCreate {
	ecc.mutation.SetBelongsToID(id)
	return ecc
}

// SetNillableBelongsToID sets the "belongsTo" edge to the EntPost entity by ID if the given value is not nil.
func (ecc *EntCommentCreate) SetNillableBelongsToID(id *int) *EntCommentCreate {
	if id != nil {
		ecc = ecc.SetBelongsToID(*id)
	}
	return ecc
}

// SetBelongsTo sets the "belongsTo" edge to the EntPost entity.
func (ecc *EntCommentCreate) SetBelongsTo(e *EntPost) *EntCommentCreate {
	return ecc.SetBelongsToID(e.ID)
}

// SetOwnedByID sets the "ownedBy" edge to the EntUser entity by ID.
func (ecc *EntCommentCreate) SetOwnedByID(id int) *EntCommentCreate {
	ecc.mutation.SetOwnedByID(id)
	return ecc
}

// SetNillableOwnedByID sets the "ownedBy" edge to the EntUser entity by ID if the given value is not nil.
func (ecc *EntCommentCreate) SetNillableOwnedByID(id *int) *EntCommentCreate {
	if id != nil {
		ecc = ecc.SetOwnedByID(*id)
	}
	return ecc
}

// SetOwnedBy sets the "ownedBy" edge to the EntUser entity.
func (ecc *EntCommentCreate) SetOwnedBy(e *EntUser) *EntCommentCreate {
	return ecc.SetOwnedByID(e.ID)
}

// Mutation returns the EntCommentMutation object of the builder.
func (ecc *EntCommentCreate) Mutation() *EntCommentMutation {
	return ecc.mutation
}

// Save creates the EntComment in the database.
func (ecc *EntCommentCreate) Save(ctx context.Context) (*EntComment, error) {
	var (
		err  error
		node *EntComment
	)
	ecc.defaults()
	if len(ecc.hooks) == 0 {
		if err = ecc.check(); err != nil {
			return nil, err
		}
		node, err = ecc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntCommentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ecc.check(); err != nil {
				return nil, err
			}
			ecc.mutation = mutation
			if node, err = ecc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ecc.hooks) - 1; i >= 0; i-- {
			if ecc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ecc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ecc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*EntComment)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EntCommentMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ecc *EntCommentCreate) SaveX(ctx context.Context) *EntComment {
	v, err := ecc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecc *EntCommentCreate) Exec(ctx context.Context) error {
	_, err := ecc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecc *EntCommentCreate) ExecX(ctx context.Context) {
	if err := ecc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ecc *EntCommentCreate) defaults() {
	if _, ok := ecc.mutation.CreatedAt(); !ok {
		v := entcomment.DefaultCreatedAt()
		ecc.mutation.SetCreatedAt(v)
	}
	if _, ok := ecc.mutation.UpdatedAt(); !ok {
		v := entcomment.DefaultUpdatedAt()
		ecc.mutation.SetUpdatedAt(v)
	}
	if _, ok := ecc.mutation.Timestamp(); !ok {
		v := entcomment.DefaultTimestamp
		ecc.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ecc *EntCommentCreate) check() error {
	if _, ok := ecc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "EntComment.createdAt"`)}
	}
	if _, ok := ecc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "EntComment.updatedAt"`)}
	}
	if _, ok := ecc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "EntComment.timestamp"`)}
	}
	if v, ok := ecc.mutation.Share(); ok {
		if err := entcomment.ShareValidator(v); err != nil {
			return &ValidationError{Name: "share", err: fmt.Errorf(`ent: validator failed for field "EntComment.share": %w`, err)}
		}
	}
	return nil
}

func (ecc *EntCommentCreate) sqlSave(ctx context.Context) (*EntComment, error) {
	_node, _spec := ecc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ecc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ecc *EntCommentCreate) createSpec() (*EntComment, *sqlgraph.CreateSpec) {
	var (
		_node = &EntComment{config: ecc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: entcomment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entcomment.FieldID,
			},
		}
	)
	if value, ok := ecc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: entcomment.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := ecc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: entcomment.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := ecc.mutation.Timestamp(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: entcomment.FieldTimestamp,
		})
		_node.Timestamp = value
	}
	if value, ok := ecc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entcomment.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := ecc.mutation.Share(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: entcomment.FieldShare,
		})
		_node.Share = value
	}
	if nodes := ecc.mutation.BelongsToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entcomment.BelongsToTable,
			Columns: []string{entcomment.BelongsToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entpost.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ent_post_comment = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ecc.mutation.OwnedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entcomment.OwnedByTable,
			Columns: []string{entcomment.OwnedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: entuser.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ent_user_comment = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntCommentCreateBulk is the builder for creating many EntComment entities in bulk.
type EntCommentCreateBulk struct {
	config
	builders []*EntCommentCreate
}

// Save creates the EntComment entities in the database.
func (eccb *EntCommentCreateBulk) Save(ctx context.Context) ([]*EntComment, error) {
	specs := make([]*sqlgraph.CreateSpec, len(eccb.builders))
	nodes := make([]*EntComment, len(eccb.builders))
	mutators := make([]Mutator, len(eccb.builders))
	for i := range eccb.builders {
		func(i int, root context.Context) {
			builder := eccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntCommentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eccb *EntCommentCreateBulk) SaveX(ctx context.Context) []*EntComment {
	v, err := eccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eccb *EntCommentCreateBulk) Exec(ctx context.Context) error {
	_, err := eccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eccb *EntCommentCreateBulk) ExecX(ctx context.Context) {
	if err := eccb.Exec(ctx); err != nil {
		panic(err)
	}
}
