// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/model/ent/entattendance"
	"backend/internal/model/ent/entcomment"
	"backend/internal/model/ent/entcourse"
	"backend/internal/model/ent/entpost"
	"backend/internal/model/ent/enttodo"
	"backend/internal/model/ent/entuser"
	"backend/internal/model/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entattendanceMixin := schema.EntAttendance{}.Mixin()
	entattendanceMixinFields0 := entattendanceMixin[0].Fields()
	_ = entattendanceMixinFields0
	entattendanceFields := schema.EntAttendance{}.Fields()
	_ = entattendanceFields
	// entattendanceDescCreatedAt is the schema descriptor for createdAt field.
	entattendanceDescCreatedAt := entattendanceMixinFields0[0].Descriptor()
	// entattendance.DefaultCreatedAt holds the default value on creation for the createdAt field.
	entattendance.DefaultCreatedAt = entattendanceDescCreatedAt.Default.(func() time.Time)
	// entattendanceDescUpdatedAt is the schema descriptor for updatedAt field.
	entattendanceDescUpdatedAt := entattendanceMixinFields0[1].Descriptor()
	// entattendance.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	entattendance.DefaultUpdatedAt = entattendanceDescUpdatedAt.Default.(func() time.Time)
	// entattendance.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	entattendance.UpdateDefaultUpdatedAt = entattendanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entattendanceDescHours is the schema descriptor for hours field.
	entattendanceDescHours := entattendanceFields[5].Descriptor()
	// entattendance.HoursValidator is a validator for the "hours" field. It is called by the builders before save.
	entattendance.HoursValidator = entattendanceDescHours.Validators[0].(func(float64) error)
	// entattendanceDescCheckedByTutor is the schema descriptor for checkedByTutor field.
	entattendanceDescCheckedByTutor := entattendanceFields[6].Descriptor()
	// entattendance.DefaultCheckedByTutor holds the default value on creation for the checkedByTutor field.
	entattendance.DefaultCheckedByTutor = entattendanceDescCheckedByTutor.Default.(bool)
	// entattendanceDescCheckedByStudent is the schema descriptor for checkedByStudent field.
	entattendanceDescCheckedByStudent := entattendanceFields[7].Descriptor()
	// entattendance.DefaultCheckedByStudent holds the default value on creation for the checkedByStudent field.
	entattendance.DefaultCheckedByStudent = entattendanceDescCheckedByStudent.Default.(bool)
	// entattendanceDescCheckedByParent is the schema descriptor for checkedByParent field.
	entattendanceDescCheckedByParent := entattendanceFields[8].Descriptor()
	// entattendance.DefaultCheckedByParent holds the default value on creation for the checkedByParent field.
	entattendance.DefaultCheckedByParent = entattendanceDescCheckedByParent.Default.(bool)
	entcommentMixin := schema.EntComment{}.Mixin()
	entcommentMixinFields0 := entcommentMixin[0].Fields()
	_ = entcommentMixinFields0
	entcommentFields := schema.EntComment{}.Fields()
	_ = entcommentFields
	// entcommentDescCreatedAt is the schema descriptor for createdAt field.
	entcommentDescCreatedAt := entcommentMixinFields0[0].Descriptor()
	// entcomment.DefaultCreatedAt holds the default value on creation for the createdAt field.
	entcomment.DefaultCreatedAt = entcommentDescCreatedAt.Default.(func() time.Time)
	// entcommentDescUpdatedAt is the schema descriptor for updatedAt field.
	entcommentDescUpdatedAt := entcommentMixinFields0[1].Descriptor()
	// entcomment.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	entcomment.DefaultUpdatedAt = entcommentDescUpdatedAt.Default.(func() time.Time)
	// entcomment.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	entcomment.UpdateDefaultUpdatedAt = entcommentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entcommentDescTimestamp is the schema descriptor for timestamp field.
	entcommentDescTimestamp := entcommentFields[0].Descriptor()
	// entcomment.DefaultTimestamp holds the default value on creation for the timestamp field.
	entcomment.DefaultTimestamp = entcommentDescTimestamp.Default.(time.Time)
	// entcommentDescContent is the schema descriptor for content field.
	entcommentDescContent := entcommentFields[1].Descriptor()
	// entcomment.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	entcomment.ContentValidator = entcommentDescContent.Validators[0].(func(string) error)
	entcourseMixin := schema.EntCourse{}.Mixin()
	entcourseMixinFields0 := entcourseMixin[0].Fields()
	_ = entcourseMixinFields0
	entcourseFields := schema.EntCourse{}.Fields()
	_ = entcourseFields
	// entcourseDescCreatedAt is the schema descriptor for createdAt field.
	entcourseDescCreatedAt := entcourseMixinFields0[0].Descriptor()
	// entcourse.DefaultCreatedAt holds the default value on creation for the createdAt field.
	entcourse.DefaultCreatedAt = entcourseDescCreatedAt.Default.(func() time.Time)
	// entcourseDescUpdatedAt is the schema descriptor for updatedAt field.
	entcourseDescUpdatedAt := entcourseMixinFields0[1].Descriptor()
	// entcourse.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	entcourse.DefaultUpdatedAt = entcourseDescUpdatedAt.Default.(func() time.Time)
	// entcourse.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	entcourse.UpdateDefaultUpdatedAt = entcourseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entcourseDescName is the schema descriptor for name field.
	entcourseDescName := entcourseFields[0].Descriptor()
	// entcourse.NameValidator is a validator for the "name" field. It is called by the builders before save.
	entcourse.NameValidator = entcourseDescName.Validators[0].(func(string) error)
	// entcourseDescCourseUrl is the schema descriptor for courseUrl field.
	entcourseDescCourseUrl := entcourseFields[1].Descriptor()
	// entcourse.CourseUrlValidator is a validator for the "courseUrl" field. It is called by the builders before save.
	entcourse.CourseUrlValidator = entcourseDescCourseUrl.Validators[0].(func(string) error)
	// entcourseDescPaymentAmount is the schema descriptor for paymentAmount field.
	entcourseDescPaymentAmount := entcourseFields[3].Descriptor()
	// entcourse.PaymentAmountValidator is a validator for the "paymentAmount" field. It is called by the builders before save.
	entcourse.PaymentAmountValidator = entcourseDescPaymentAmount.Validators[0].(func(float64) error)
	// entcourseDescMonday is the schema descriptor for monday field.
	entcourseDescMonday := entcourseFields[6].Descriptor()
	// entcourse.DefaultMonday holds the default value on creation for the monday field.
	entcourse.DefaultMonday = entcourseDescMonday.Default.(bool)
	// entcourseDescTuesday is the schema descriptor for tuesday field.
	entcourseDescTuesday := entcourseFields[7].Descriptor()
	// entcourse.DefaultTuesday holds the default value on creation for the tuesday field.
	entcourse.DefaultTuesday = entcourseDescTuesday.Default.(bool)
	// entcourseDescWednesday is the schema descriptor for wednesday field.
	entcourseDescWednesday := entcourseFields[8].Descriptor()
	// entcourse.DefaultWednesday holds the default value on creation for the wednesday field.
	entcourse.DefaultWednesday = entcourseDescWednesday.Default.(bool)
	// entcourseDescThursday is the schema descriptor for thursday field.
	entcourseDescThursday := entcourseFields[9].Descriptor()
	// entcourse.DefaultThursday holds the default value on creation for the thursday field.
	entcourse.DefaultThursday = entcourseDescThursday.Default.(bool)
	// entcourseDescFriday is the schema descriptor for friday field.
	entcourseDescFriday := entcourseFields[10].Descriptor()
	// entcourse.DefaultFriday holds the default value on creation for the friday field.
	entcourse.DefaultFriday = entcourseDescFriday.Default.(bool)
	// entcourseDescSaturday is the schema descriptor for saturday field.
	entcourseDescSaturday := entcourseFields[11].Descriptor()
	// entcourse.DefaultSaturday holds the default value on creation for the saturday field.
	entcourse.DefaultSaturday = entcourseDescSaturday.Default.(bool)
	// entcourseDescSunday is the schema descriptor for sunday field.
	entcourseDescSunday := entcourseFields[12].Descriptor()
	// entcourse.DefaultSunday holds the default value on creation for the sunday field.
	entcourse.DefaultSunday = entcourseDescSunday.Default.(bool)
	entpostMixin := schema.EntPost{}.Mixin()
	entpostMixinFields0 := entpostMixin[0].Fields()
	_ = entpostMixinFields0
	entpostFields := schema.EntPost{}.Fields()
	_ = entpostFields
	// entpostDescCreatedAt is the schema descriptor for createdAt field.
	entpostDescCreatedAt := entpostMixinFields0[0].Descriptor()
	// entpost.DefaultCreatedAt holds the default value on creation for the createdAt field.
	entpost.DefaultCreatedAt = entpostDescCreatedAt.Default.(func() time.Time)
	// entpostDescUpdatedAt is the schema descriptor for updatedAt field.
	entpostDescUpdatedAt := entpostMixinFields0[1].Descriptor()
	// entpost.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	entpost.DefaultUpdatedAt = entpostDescUpdatedAt.Default.(func() time.Time)
	// entpost.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	entpost.UpdateDefaultUpdatedAt = entpostDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entpostDescTimestamp is the schema descriptor for timestamp field.
	entpostDescTimestamp := entpostFields[0].Descriptor()
	// entpost.DefaultTimestamp holds the default value on creation for the timestamp field.
	entpost.DefaultTimestamp = entpostDescTimestamp.Default.(time.Time)
	// entpostDescContent is the schema descriptor for content field.
	entpostDescContent := entpostFields[1].Descriptor()
	// entpost.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	entpost.ContentValidator = entpostDescContent.Validators[0].(func(string) error)
	enttodoMixin := schema.EntTodo{}.Mixin()
	enttodoMixinFields0 := enttodoMixin[0].Fields()
	_ = enttodoMixinFields0
	enttodoFields := schema.EntTodo{}.Fields()
	_ = enttodoFields
	// enttodoDescCreatedAt is the schema descriptor for createdAt field.
	enttodoDescCreatedAt := enttodoMixinFields0[0].Descriptor()
	// enttodo.DefaultCreatedAt holds the default value on creation for the createdAt field.
	enttodo.DefaultCreatedAt = enttodoDescCreatedAt.Default.(func() time.Time)
	// enttodoDescUpdatedAt is the schema descriptor for updatedAt field.
	enttodoDescUpdatedAt := enttodoMixinFields0[1].Descriptor()
	// enttodo.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	enttodo.DefaultUpdatedAt = enttodoDescUpdatedAt.Default.(func() time.Time)
	// enttodo.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	enttodo.UpdateDefaultUpdatedAt = enttodoDescUpdatedAt.UpdateDefault.(func() time.Time)
	entuserMixin := schema.EntUser{}.Mixin()
	entuserMixinFields0 := entuserMixin[0].Fields()
	_ = entuserMixinFields0
	entuserFields := schema.EntUser{}.Fields()
	_ = entuserFields
	// entuserDescCreatedAt is the schema descriptor for createdAt field.
	entuserDescCreatedAt := entuserMixinFields0[0].Descriptor()
	// entuser.DefaultCreatedAt holds the default value on creation for the createdAt field.
	entuser.DefaultCreatedAt = entuserDescCreatedAt.Default.(func() time.Time)
	// entuserDescUpdatedAt is the schema descriptor for updatedAt field.
	entuserDescUpdatedAt := entuserMixinFields0[1].Descriptor()
	// entuser.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	entuser.DefaultUpdatedAt = entuserDescUpdatedAt.Default.(func() time.Time)
	// entuser.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	entuser.UpdateDefaultUpdatedAt = entuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entuserDescFirstName is the schema descriptor for firstName field.
	entuserDescFirstName := entuserFields[0].Descriptor()
	// entuser.FirstNameValidator is a validator for the "firstName" field. It is called by the builders before save.
	entuser.FirstNameValidator = func() func(string) error {
		validators := entuserDescFirstName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(firstName string) error {
			for _, fn := range fns {
				if err := fn(firstName); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// entuserDescLastName is the schema descriptor for lastName field.
	entuserDescLastName := entuserFields[1].Descriptor()
	// entuser.LastNameValidator is a validator for the "lastName" field. It is called by the builders before save.
	entuser.LastNameValidator = func() func(string) error {
		validators := entuserDescLastName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(lastName string) error {
			for _, fn := range fns {
				if err := fn(lastName); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// entuserDescEmail is the schema descriptor for email field.
	entuserDescEmail := entuserFields[2].Descriptor()
	// entuser.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	entuser.EmailValidator = func() func(string) error {
		validators := entuserDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// entuserDescPassword is the schema descriptor for password field.
	entuserDescPassword := entuserFields[3].Descriptor()
	// entuser.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	entuser.PasswordValidator = entuserDescPassword.Validators[0].(func(string) error)
	// entuserDescCountry is the schema descriptor for country field.
	entuserDescCountry := entuserFields[4].Descriptor()
	// entuser.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	entuser.CountryValidator = entuserDescCountry.Validators[0].(func(string) error)
	// entuserDescPhone is the schema descriptor for phone field.
	entuserDescPhone := entuserFields[5].Descriptor()
	// entuser.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	entuser.PhoneValidator = func() func(string) error {
		validators := entuserDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// entuserDescIsTutor is the schema descriptor for isTutor field.
	entuserDescIsTutor := entuserFields[8].Descriptor()
	// entuser.DefaultIsTutor holds the default value on creation for the isTutor field.
	entuser.DefaultIsTutor = entuserDescIsTutor.Default.(bool)
	// entuserDescIsStudent is the schema descriptor for isStudent field.
	entuserDescIsStudent := entuserFields[9].Descriptor()
	// entuser.DefaultIsStudent holds the default value on creation for the isStudent field.
	entuser.DefaultIsStudent = entuserDescIsStudent.Default.(bool)
	// entuserDescIsParent is the schema descriptor for isParent field.
	entuserDescIsParent := entuserFields[10].Descriptor()
	// entuser.DefaultIsParent holds the default value on creation for the isParent field.
	entuser.DefaultIsParent = entuserDescIsParent.Default.(bool)
}
