// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/entcomment"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// EntComment is the model entity for the EntComment schema.
type EntComment struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntComment) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case entcomment.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EntComment", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntComment fields.
func (ec *EntComment) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entcomment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ec.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this EntComment.
// Note that you need to call EntComment.Unwrap() before calling this method if this EntComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (ec *EntComment) Update() *EntCommentUpdateOne {
	return (&EntCommentClient{config: ec.config}).UpdateOne(ec)
}

// Unwrap unwraps the EntComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ec *EntComment) Unwrap() *EntComment {
	_tx, ok := ec.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntComment is not a transactional entity")
	}
	ec.config.driver = _tx.drv
	return ec
}

// String implements the fmt.Stringer.
func (ec *EntComment) String() string {
	var builder strings.Builder
	builder.WriteString("EntComment(")
	builder.WriteString(fmt.Sprintf("id=%v", ec.ID))
	builder.WriteByte(')')
	return builder.String()
}

// EntComments is a parsable slice of EntComment.
type EntComments []*EntComment

func (ec EntComments) config(cfg config) {
	for _i := range ec {
		ec[_i].config = cfg
	}
}
