// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/entpost"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// EntPost is the model entity for the EntPost schema.
type EntPost struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntPost) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case entpost.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EntPost", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntPost fields.
func (ep *EntPost) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entpost.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ep.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this EntPost.
// Note that you need to call EntPost.Unwrap() before calling this method if this EntPost
// was returned from a transaction, and the transaction was committed or rolled back.
func (ep *EntPost) Update() *EntPostUpdateOne {
	return (&EntPostClient{config: ep.config}).UpdateOne(ep)
}

// Unwrap unwraps the EntPost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ep *EntPost) Unwrap() *EntPost {
	_tx, ok := ep.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntPost is not a transactional entity")
	}
	ep.config.driver = _tx.drv
	return ep
}

// String implements the fmt.Stringer.
func (ep *EntPost) String() string {
	var builder strings.Builder
	builder.WriteString("EntPost(")
	builder.WriteString(fmt.Sprintf("id=%v", ep.ID))
	builder.WriteByte(')')
	return builder.String()
}

// EntPosts is a parsable slice of EntPost.
type EntPosts []*EntPost

func (ep EntPosts) config(cfg config) {
	for _i := range ep {
		ep[_i].config = cfg
	}
}
