// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/enttodo"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// EntTodo is the model entity for the EntTodo schema.
type EntTodo struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntTodo) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case enttodo.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EntTodo", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntTodo fields.
func (et *EntTodo) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enttodo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			et.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this EntTodo.
// Note that you need to call EntTodo.Unwrap() before calling this method if this EntTodo
// was returned from a transaction, and the transaction was committed or rolled back.
func (et *EntTodo) Update() *EntTodoUpdateOne {
	return (&EntTodoClient{config: et.config}).UpdateOne(et)
}

// Unwrap unwraps the EntTodo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (et *EntTodo) Unwrap() *EntTodo {
	_tx, ok := et.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntTodo is not a transactional entity")
	}
	et.config.driver = _tx.drv
	return et
}

// String implements the fmt.Stringer.
func (et *EntTodo) String() string {
	var builder strings.Builder
	builder.WriteString("EntTodo(")
	builder.WriteString(fmt.Sprintf("id=%v", et.ID))
	builder.WriteByte(')')
	return builder.String()
}

// EntTodos is a parsable slice of EntTodo.
type EntTodos []*EntTodo

func (et EntTodos) config(cfg config) {
	for _i := range et {
		et[_i].config = cfg
	}
}
