// Code generated by ent, DO NOT EDIT.

package entattendance

import (
	"backend/internal/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDate), v))
	})
}

// StartTime applies equality check predicate on the "startTime" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStartTime), v))
	})
}

// EndTime applies equality check predicate on the "endTime" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEndTime), v))
	})
}

// Day applies equality check predicate on the "day" field. It's identical to DayEQ.
func Day(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDay), v))
	})
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNote), v))
	})
}

// Hours applies equality check predicate on the "hours" field. It's identical to HoursEQ.
func Hours(v float64) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHours), v))
	})
}

// CheckedByTutor applies equality check predicate on the "checkedByTutor" field. It's identical to CheckedByTutorEQ.
func CheckedByTutor(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCheckedByTutor), v))
	})
}

// CheckedByStudent applies equality check predicate on the "checkedByStudent" field. It's identical to CheckedByStudentEQ.
func CheckedByStudent(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCheckedByStudent), v))
	})
}

// CheckedByParent applies equality check predicate on the "checkedByParent" field. It's identical to CheckedByParentEQ.
func CheckedByParent(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCheckedByParent), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDate), v))
	})
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDate), v))
	})
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDate), v...))
	})
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDate), v...))
	})
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDate), v))
	})
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDate), v))
	})
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDate), v))
	})
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDate), v))
	})
}

// StartTimeEQ applies the EQ predicate on the "startTime" field.
func StartTimeEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStartTime), v))
	})
}

// StartTimeNEQ applies the NEQ predicate on the "startTime" field.
func StartTimeNEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStartTime), v))
	})
}

// StartTimeIn applies the In predicate on the "startTime" field.
func StartTimeIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldStartTime), v...))
	})
}

// StartTimeNotIn applies the NotIn predicate on the "startTime" field.
func StartTimeNotIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldStartTime), v...))
	})
}

// StartTimeGT applies the GT predicate on the "startTime" field.
func StartTimeGT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStartTime), v))
	})
}

// StartTimeGTE applies the GTE predicate on the "startTime" field.
func StartTimeGTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStartTime), v))
	})
}

// StartTimeLT applies the LT predicate on the "startTime" field.
func StartTimeLT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStartTime), v))
	})
}

// StartTimeLTE applies the LTE predicate on the "startTime" field.
func StartTimeLTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStartTime), v))
	})
}

// EndTimeEQ applies the EQ predicate on the "endTime" field.
func EndTimeEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEndTime), v))
	})
}

// EndTimeNEQ applies the NEQ predicate on the "endTime" field.
func EndTimeNEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEndTime), v))
	})
}

// EndTimeIn applies the In predicate on the "endTime" field.
func EndTimeIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldEndTime), v...))
	})
}

// EndTimeNotIn applies the NotIn predicate on the "endTime" field.
func EndTimeNotIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldEndTime), v...))
	})
}

// EndTimeGT applies the GT predicate on the "endTime" field.
func EndTimeGT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEndTime), v))
	})
}

// EndTimeGTE applies the GTE predicate on the "endTime" field.
func EndTimeGTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEndTime), v))
	})
}

// EndTimeLT applies the LT predicate on the "endTime" field.
func EndTimeLT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEndTime), v))
	})
}

// EndTimeLTE applies the LTE predicate on the "endTime" field.
func EndTimeLTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEndTime), v))
	})
}

// DayEQ applies the EQ predicate on the "day" field.
func DayEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDay), v))
	})
}

// DayNEQ applies the NEQ predicate on the "day" field.
func DayNEQ(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDay), v))
	})
}

// DayIn applies the In predicate on the "day" field.
func DayIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDay), v...))
	})
}

// DayNotIn applies the NotIn predicate on the "day" field.
func DayNotIn(vs ...time.Time) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDay), v...))
	})
}

// DayGT applies the GT predicate on the "day" field.
func DayGT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDay), v))
	})
}

// DayGTE applies the GTE predicate on the "day" field.
func DayGTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDay), v))
	})
}

// DayLT applies the LT predicate on the "day" field.
func DayLT(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDay), v))
	})
}

// DayLTE applies the LTE predicate on the "day" field.
func DayLTE(v time.Time) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDay), v))
	})
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNote), v))
	})
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNote), v))
	})
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldNote), v...))
	})
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldNote), v...))
	})
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNote), v))
	})
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNote), v))
	})
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNote), v))
	})
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNote), v))
	})
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNote), v))
	})
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNote), v))
	})
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNote), v))
	})
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldNote)))
	})
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldNote)))
	})
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNote), v))
	})
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNote), v))
	})
}

// HoursEQ applies the EQ predicate on the "hours" field.
func HoursEQ(v float64) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHours), v))
	})
}

// HoursNEQ applies the NEQ predicate on the "hours" field.
func HoursNEQ(v float64) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldHours), v))
	})
}

// HoursIn applies the In predicate on the "hours" field.
func HoursIn(vs ...float64) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldHours), v...))
	})
}

// HoursNotIn applies the NotIn predicate on the "hours" field.
func HoursNotIn(vs ...float64) predicate.EntAttendance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldHours), v...))
	})
}

// HoursGT applies the GT predicate on the "hours" field.
func HoursGT(v float64) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldHours), v))
	})
}

// HoursGTE applies the GTE predicate on the "hours" field.
func HoursGTE(v float64) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldHours), v))
	})
}

// HoursLT applies the LT predicate on the "hours" field.
func HoursLT(v float64) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldHours), v))
	})
}

// HoursLTE applies the LTE predicate on the "hours" field.
func HoursLTE(v float64) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldHours), v))
	})
}

// HoursIsNil applies the IsNil predicate on the "hours" field.
func HoursIsNil() predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldHours)))
	})
}

// HoursNotNil applies the NotNil predicate on the "hours" field.
func HoursNotNil() predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldHours)))
	})
}

// CheckedByTutorEQ applies the EQ predicate on the "checkedByTutor" field.
func CheckedByTutorEQ(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCheckedByTutor), v))
	})
}

// CheckedByTutorNEQ applies the NEQ predicate on the "checkedByTutor" field.
func CheckedByTutorNEQ(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCheckedByTutor), v))
	})
}

// CheckedByStudentEQ applies the EQ predicate on the "checkedByStudent" field.
func CheckedByStudentEQ(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCheckedByStudent), v))
	})
}

// CheckedByStudentNEQ applies the NEQ predicate on the "checkedByStudent" field.
func CheckedByStudentNEQ(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCheckedByStudent), v))
	})
}

// CheckedByParentEQ applies the EQ predicate on the "checkedByParent" field.
func CheckedByParentEQ(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCheckedByParent), v))
	})
}

// CheckedByParentNEQ applies the NEQ predicate on the "checkedByParent" field.
func CheckedByParentNEQ(v bool) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCheckedByParent), v))
	})
}

// HasAttendanceFor applies the HasEdge predicate on the "attendanceFor" edge.
func HasAttendanceFor() predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AttendanceForTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AttendanceForTable, AttendanceForColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttendanceForWith applies the HasEdge predicate on the "attendanceFor" edge with a given conditions (other predicates).
func HasAttendanceForWith(preds ...predicate.EntCourse) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AttendanceForInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AttendanceForTable, AttendanceForColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnedBy applies the HasEdge predicate on the "ownedBy" edge.
func HasOwnedBy() predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnedByTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnedByTable, OwnedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnedByWith applies the HasEdge predicate on the "ownedBy" edge with a given conditions (other predicates).
func HasOwnedByWith(preds ...predicate.EntUser) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnedByInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnedByTable, OwnedByColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EntAttendance) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EntAttendance) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EntAttendance) predicate.EntAttendance {
	return predicate.EntAttendance(func(s *sql.Selector) {
		p(s.Not())
	})
}
